#############################################################################
# Makefile for building: voxel
# Generated by qmake (2.01a) (Qt 4.8.1) on: Sat Nov 23 12:29:42 2013
# Project:  voxel.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile voxel.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -L/usr/local/lib/ -lsfml-graphics-d -lsfml-window-d -lsfml-audio-d -lsfml-system-d -lGL -lGLU -lGLEW -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = .obj/

####### Files

SOURCES       = src/main.cpp \
		src/Renderer.cpp \
		src/Chunk.cpp \
		src/Block.cpp \
		src/Freeflycamera.cpp \
		src/Vector3d.cpp \
		src/ChunkManager.cpp \
		src/Mesh.cpp \
		src/LocalChunkSystem.cpp \
		src/VectorTools.cpp 
OBJECTS       = .obj/main.o \
		.obj/Renderer.o \
		.obj/Chunk.o \
		.obj/Block.o \
		.obj/Freeflycamera.o \
		.obj/Vector3d.o \
		.obj/ChunkManager.o \
		.obj/Mesh.o \
		.obj/LocalChunkSystem.o \
		.obj/VectorTools.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		voxel.pro
QMAKE_TARGET  = voxel
DESTDIR       = 
TARGET        = voxel

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: voxel.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile voxel.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/declarative_debug.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile voxel.pro

dist: 
	@$(CHK_DIR_EXISTS) .obj/voxel1.0.0 || $(MKDIR) .obj/voxel1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .obj/voxel1.0.0/ && $(COPY_FILE) --parents src/Renderer.hpp src/Chunk.hpp src/Block.hpp src/Freeflycamera.h src/Vector3d.h src/Mesh.hpp src/LocalChunkSystem.hpp src/VectorTools.hpp src/ChunkManager.hpp .obj/voxel1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/Renderer.cpp src/Chunk.cpp src/Block.cpp src/Freeflycamera.cpp src/Vector3d.cpp src/ChunkManager.cpp src/Mesh.cpp src/LocalChunkSystem.cpp src/VectorTools.cpp .obj/voxel1.0.0/ && (cd `dirname .obj/voxel1.0.0` && $(TAR) voxel1.0.0.tar voxel1.0.0 && $(COMPRESS) voxel1.0.0.tar) && $(MOVE) `dirname .obj/voxel1.0.0`/voxel1.0.0.tar.gz . && $(DEL_FILE) -r .obj/voxel1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

.obj/main.o: src/main.cpp src/Renderer.hpp \
		src/Chunk.hpp \
		src/Block.hpp \
		src/Mesh.hpp \
		src/Freeflycamera.h \
		src/Vector3d.h \
		src/ChunkManager.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/main.o src/main.cpp

.obj/Renderer.o: src/Renderer.cpp src/Renderer.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/Renderer.o src/Renderer.cpp

.obj/Chunk.o: src/Chunk.cpp src/Block.hpp \
		src/Chunk.hpp \
		src/Renderer.hpp \
		src/Mesh.hpp \
		src/ChunkManager.hpp \
		src/LocalChunkSystem.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/Chunk.o src/Chunk.cpp

.obj/Block.o: src/Block.cpp src/Block.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/Block.o src/Block.cpp

.obj/Freeflycamera.o: src/Freeflycamera.cpp src/Freeflycamera.h \
		src/Vector3d.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/Freeflycamera.o src/Freeflycamera.cpp

.obj/Vector3d.o: src/Vector3d.cpp src/Vector3d.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/Vector3d.o src/Vector3d.cpp

.obj/ChunkManager.o: src/ChunkManager.cpp src/Mesh.hpp \
		src/Renderer.hpp \
		src/VectorTools.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/ChunkManager.o src/ChunkManager.cpp

.obj/Mesh.o: src/Mesh.cpp src/Mesh.hpp \
		src/Renderer.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/Mesh.o src/Mesh.cpp

.obj/LocalChunkSystem.o: src/LocalChunkSystem.cpp src/LocalChunkSystem.hpp \
		src/Chunk.hpp \
		src/Renderer.hpp \
		src/Block.hpp \
		src/Mesh.hpp \
		src/VectorTools.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/LocalChunkSystem.o src/LocalChunkSystem.cpp

.obj/VectorTools.o: src/VectorTools.cpp src/VectorTools.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/VectorTools.o src/VectorTools.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

